### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by tripolar** [erikd/libsndfile#466] opened 2019-04-16 18:06 UTC
The number of unfixed CVEs in 1.0.28 piles up and i would propose to release a new version to get a new clean stable version that doesn't need  a lot of patches to get it CVE free

**Comment by evpobr** [comment] 2019-04-17 05:50
Duplicate of #436

**Comment by erikd** [comment] 2019-04-20 12:52
Its is coming.

**Closed by erikd** 2019-04-20 12:52 UTC
