### ISSUE TITLE
python scikits.audiolab Sndfile special chars in file name

### ISSUE THREAD

**Issue by Fuqran** [erikd/libsndfile#74] opened 2014-08-18 16:12 UTC
Hi ,

Could you help me out on this , or guide me to some how can thanks 
(python scikits.audiolab Sndfile special chars in file name)
I am trying to get a wav file information but Sndfile is unable to read file with special characters in path and file name(查找問題daw.wav) and i am unable to get information in any way , i tried passing file path to Sndfile  with diferent encoding to but didnt work , but if i pass this 'C:\Users\Furqan\Desktop\test\DAW\1.wav' it works fine , Thanks is advance 

My Code is 
    # -*- coding: UTF-8 -*-
    from scikits.audiolab import Sndfile
    from os import walk, path, stat

    track1 =  r'C:\Users\Furqan\Desktop\test\查找問題daw\查找問題d.wav'
    #track2 = r'C:\Users\Furqan\Desktop\test\DAW\1.wav'

    try:
        track_one_file_obj = Sndfile(track1, 'r')
    except:
        print('Simple didnt work')
        pass

    try:
        track_one_file_obj = Sndfile(track1.decode('cp1252'), 'r')
    except:
        print('cp1252 didnt work')
        pass

    try:
        track_one_file_obj = Sndfile(track1.encode('utf-8'), 'r')
        print(track_one_file_obj)
    except:
        print('encode didnt work')
        pass

    try:
        track_one_file_obj = Sndfile(track1.encode('utf8'), 'r')
        print(track_one_file_obj)
    except:
        print('encode didnt work')
        pass

    try:
        track_one_file_obj = Sndfile(track1.decode('utf-8'), 'r')
        print(track_one_file_obj)
    except:
        print('decode didnt work')
        pass

**Comment by mgeier** [comment] 2015-10-26 16:23
I think this issue can be closed, since it is a duplicate of https://github.com/cournape/audiolab/issues/26.

There isn't too much activity in the scikits.audiolab project, so I guess this will not be fixed anytime soon. But in the meantime, everyone who is interested should have a look at [PySoundFile](http://pysoundfile.readthedocs.org/), which since version 0.8.0 uses `sf_wchar_open()` for Unicode file names on Windows, which solves the abovementioned problems.

**Closed** 2015-10-26 21:45 UTC
