### ISSUE TITLE
Look into adding a parallel CMake build system.

### ISSUE THREAD

**Issue by erikd** [erikd/libsndfile#71] opened 2014-07-12 02:47 UTC
CMake has one large advantage, it can generate Visual Studio project files.

**Comment by syb0rg** [comment] 2016-07-11 13:17
With LibSndFile's dependencies such as FLAC, do you want [ExternalProject](https://cmake.org/cmake/help/v3.0/module/ExternalProject.html) integration to handle them?  This could be set up to then download and build the dependency library as needed, instead of relying on the user to install it themselves.

**Comment by erikd** [comment] 2016-07-11 20:12
Can it be made optional? For most Linux systems (and brew I suppose) the best solution is to use the distro packages, but elsewhere that's probably not the case.

**Comment by syb0rg** [comment] 2016-07-11 20:15
Actually, in few cases (with brew AFAIK) using ExternalProject is better as brew on occasion doesn't have the most up-to-date software packages available.   

What do you mean optional?  I know you can compile LibSndFile without FLAC support, do you mean like that?

**Comment by erikd** [comment] 2016-07-11 21:44
Currently libsndfile can be compiled with FLAC/ogg/vorbis or with FLAC/ogg/vorbis. That should remain the same.

By optional, I mean, use already installed versions by default.

**Comment by syb0rg** [comment] 2016-07-11 21:58
Ah, yes I have this functionality [in a few of my projects](https://github.com/syb0rg/Khronos/blob/master/cmake/Unix-ExternalProjects.txt).  It will be no problem to add.

**Comment by syb0rg** [comment] 2016-07-13 13:43
Any comments on [my latest commits](https://github.com/erikd/libsndfile/compare/master...syb0rg:master)? It's not much more from last time but it addresses the problems you commented on before.  I was able to build these on both Windows and Mac.

**Comment by erikd** [comment] 2016-07-13 20:44
On x86_64/linux it fails to build:

```
Scanning dependencies of target sndfile
[100%] Linking C shared library libsndfile.so
/usr/bin/ld: src/CMakeFiles/source.dir/aiff.c.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
src/CMakeFiles/source.dir/aiff.c.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/sndfile.dir/build.make:246: recipe for target 'libsndfile.so' failed
make[2]: *** [libsndfile.so] Error 1
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/sndfile.dir/all' failed
make[1]: *** [CMakeFiles/sndfile.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by syb0rg** [comment] 2016-07-13 20:46
Odd, I'll see if I can get my Raspberry Pi up and use it to try and reproduce.

**Comment by erikd** [comment] 2016-07-13 22:35
I also notice that *zero* warning flags are being passed the gcc. I tried
```
VERBOSE=1 CFLAGS="-Wall -Werror" make
```
and that didn't help.

**Comment by syb0rg** [comment] 2016-07-18 00:13
I'll look into a way for defining those outside of CMake, but right now it requires those types of definitions to be made within a `CMakeLists.txt` file.

As of now, I've replicated all of your previous CMake code (minus the test stuff which seemed broken?).  I've tested it on my Mac, though I expect it to fail somehow on your computer.  I've submitted erikd/libsndfile#137; I figure we can work on the system together now since the functionality is the same.

**Comment by erikd** [comment] 2016-07-18 01:03
> I'll look into a way for defining those outside of CMake, but right now it requires those types of definitions to be made within a CMakeLists.txt file.

Being able to defined extra `CFLAGS` without changing any files that are under revision control is a hard requirement. For instance, when I work on libsndfile I *always* enable `-Werror` whereas I would *never* commit that to the repo or ship it in a tarball.

> As of now, I've replicated all of your previous CMake code (minus the test stuff which seemed broken?). 

On Linux, my CMake build system the test build and all tests pass. Is it possible you are missing GNU autogen?

**Comment by syb0rg** [comment] 2016-07-18 01:09
Understood, I did some preliminary research before on solving that issue but haven't implemented it yet in my code.

The test building section in your `CMakeLists.txt` didn't run/work for me.  It also had a "fix me" in there somewhere.

**Comment by erikd** [comment] 2016-07-18 01:27
> The test building section in your CMakeLists.txt didn't run/work for me. It also had a "fix me" in there somewhere.

Sure that wasn't:
```
lsf_build_test_c (fix_this "")
```

There is a file `src/fix_this.c` that gets built into an executable.

**Comment by evpobr** [comment] 2017-03-15 07:35
Meanwhile, Visual Studio 2017 has been released, with native CMake support. It works, here is [64-bit build](https://github.com/evpobr/libsndfile/releases/tag/v1.0.28pre1).

**Comment by evpobr** [comment] 2017-04-05 13:59
Opus master #205 is merged to master, hooray. It is time for polishing now.

@erikd, can i commit to `master` directly? I talk about small changes, about CMake mostly, big changes as pull request with approving. Also, i know what do you think about that "closes " autoreferences. What about simple issue references like #160? I guess it's better to describe it in CONTRIBUTING.md.

**Closed** 2017-04-25 09:21 UTC
Labels: Wishlist
