### ISSUE TITLE
Chunk parsing bug in wavlike.c in the case of "weird-ass zero marker"

### ISSUE THREAD

**Issue by andrewoliverhall** [erikd/libsndfile#542] opened 2020-08-14 00:55 UTC
Trying to parse a file which has a LIST chunk that contains all zeros.  It gets to the case in wavlike.c where it says "found weird-ass zero marker.  jumping to the end of chunk".  However, then it jumps 4 bytes too far and fails to parse, even though there is a valid data chunk.  

Output of sndfile-info:

administrator’s-MacBook-Pro:libsndfile ahall$ sndfile-info ~/Downloads/MONO-001.WAV
Error : Not able to open input file /Users/ahall/Downloads/MONO-001.WAV.
File : /Users/ahall/Downloads/MONO-001.WAV
Length : 41569392
RIFF : 41569384
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 1
  Sample Rate   : 48000
  Block Align   : 3
  Bit Width     : 24
  Bytes/sec     : 144000
LIST : 393164
    *** Found weird-ass zero marker. Jumping to end of chunk.
Request for header allocation of 786328 denined.
    *** Offset is now : 0x5FFFC
*** Unknown chunk marker (2744C70) at position 393212. Exiting parser.
*** Chunk size 385875968 > file length 41569392. Exiting parser.

Error in WAV file. No 'data' chunk marker.

file can be found here: https://www.dropbox.com/sh/2qibk7tnday7bln/AAD09LubaAGqqacDFCIGo2Gaa?dl=0

seems to fix it if I remove the "+ 4" from the line that is calling "psf_binheader_readf" right after that print statement.

**Comment by evpobr** [comment] 2020-08-14 05:16
hello @andrewoliverhall , thanks for your report. I've tested your file:    

````
    File : .\MONO-001.WAV
    Length : 41569392
    RIFF : 41569384
    WAVE
    fmt  : 16
      Format        : 0x1 => WAVE_FORMAT_PCM
      Channels      : 1
      Sample Rate   : 48000
      Block Align   : 3
      Bit Width     : 24
      Bytes/sec     : 144000
    LIST : 393164
        *** Found weird-ass zero marker. Jumping to end of chunk.
    Request for header allocation of 786320 denied.
        *** Offset is now : 0x5FFF8
    data : 41176176
    End

    ----------------------------------------
    Sample Rate : 48000
    Frames      : 13725392
    Channels    : 1
    Format      : 0x00010003
    Sections    : 1
    Seekable    : TRUE
    Duration    : 00:04:45.946
    Signal Max  : 2.884e+06 (-9.27 dB)
````
No error. I'm pretty sure your sources are outdated. This issue is duplicate of #370, fixed by #371.

**Comment by evpobr** [comment] 2020-08-14 05:17
Duplicate of #370

**Closed by evpobr** 2020-08-14 05:16 UTC

**Comment by andrewoliverhall** [comment] 2020-08-14 13:34
oops I failed to check the latest code sorry about that.  I was just looking at the release version of my source.
