### ISSUE TITLE
Tag new version with latest cmake improvements

### ISSUE THREAD

**Issue by SylvainCorlay** [erikd/libsndfile#375] opened 2018-03-16 10:10 UTC
Version `1.0.28` fails to build with cmake on windows, while the tip of master, which includes the recent improvements to the cmake builds without issue.

I am working on the packaging for the conda package manager and if there was a new version tagged, this would make things easier on windows.

**Comment by evpobr** [comment] 2018-03-16 10:16
I agree with you, it is time for new release. There are may bugfixes in master, and even new codec added. Waiting for @erikd answer, the is the boss.

**Comment by erikd** [comment] 2018-03-16 22:11
For a new release, we need a bunch of outstanding bugs fixed.

**Comment by erikd** [comment] 2018-03-24 08:45
Anybody interested in doing any bug fixing?

**Comment by SylvainCorlay** [comment] 2018-04-20 00:14
Sorry, I am swamped with work, but I will be updating the conda package when a release is tagged!

**Comment by kastman** [comment] 2018-05-14 15:49
I'm also trying to use this in an upstream package, and would be willing to backport the `1.0.28` CMake files if you'd be interested in accepting them into the tarfile build that goes up at http://www.mega-nerd.com/libsndfile/files/ (as the version itself won't change, but the packaging would). I'm looking, but were the CMake changes relatively straightforward?

Alternatively, would love to have a new release, but I won't be able to help with the bugfixes as I'm unfamiliar with the libsndfile internals.

**Comment by erikd** [comment] 2018-05-14 23:29
There are bug fixes that should go in any new release. There are also unfixed bugs that should be fixed before a new release. Unfortunately I have almost no free time at the moment.

**Comment by kastman** [comment] 2018-05-15 01:34
@erikd to be clear I’m not proposing a new release or new version since there doesn’t seem to be a lot of spare capacity for these fixes, just a correction of the old package that would build correctly on windows. I appreciate your effort and time, and will try to patch this on the conda packaging side instead. Thanks,

**Comment by SylvainCorlay** [comment] 2018-11-22 16:17
@erikd @evpobr howdy

I am considering patching the cmake file as part of the conda recipe for the last released version. Although it is probably not worth it if a new version including the fixes is imminent. Are you guys thinking of tagging a new version in the near future?

**Comment by kastman** [comment] 2018-11-22 17:01
Hi @sylvaincorley - sorry, I meant to do this months ago.  I probably won’t have time to patch it in the near future but would appreciate it if you did!

**Comment by evpobr** [comment] 2018-11-22 18:45
@SylvainCorlay , don't know what @erikd waits. He's the boss here.

**Comment by Maryse47** [comment] 2019-02-10 16:04
Hi, first of all thank you for working on this great project.

I saw there are currently [155 new commits](https://github.com/erikd/libsndfile/compare/1.0.28...master) after last release so we can guess there are about 150 more or less severe outstanding bugfixes. I imagine that costed an enormous amount of work and time, unfortunately no user benefits from those as packagers follow project releases and backport only security patches which alone can be quite overwhelming as there are plenty of those too.

I assume that the amount of fixes is already so big that it doesn't make much difference for users if they get a dozen of fixes more in new release or they will have to wait for another one. On the other hand, not getting any fixes at all as time goes by weeks, months or years, even as they are complete may be seen as big loss.

Maybe I'm wrong but I suppose preparing a new release doesn't need as much work as working on new fixes (run a script to make a tarball, tag release on github) so making a one now would bring an immense value to the users at little cost. Please consider this.

There is an old unix mantra, _release early, release often_ which is still relevant to make successful open source projects.

Thank you.

**Comment by evpobr** [comment] 2020-08-16 11:29
Duplicate of #470

**Closed by evpobr** 2020-08-16 11:29 UTC
