### ISSUE TITLE
 When I use sndfile-info to see speex format file when the error,　　Internal error : SF_INFO struct incomplete.　　　why???

### ISSUE THREAD

**Issue by guoying1030** [erikd/libsndfile#262] opened 2017-05-09 01:23 UTC
[root@A01-R04-I221-28 2000_serving]# sndfile-info test.spx
spx_read_header 161
spx_print_comments 363
Lavf57.7.2
encoder=Lavf57.7.2
Error : Not able to open input file test.spx.
File : test.spx
Length : 24921
Ogg stream data : Speex
Stream serialno : 550089951
Speex header
  Encoder ver   : 1.2.0
  Frames/packet : 1
  Bit rate        : 42200
  Sample rate   : 16000
  Mode            : wideband (sub-band CELP)
  VBR              : no
  Channels        : 1
  Extra headers : 0
End
packet_count 2
page_nb_packets 1
page_granule *l*ld
---------------------------------
 Sample rate :   16000
 Frames      :   0
 Channels    :   1
 Format      :   0x5200000
 Sections    :   1
 Seekable    :   TRUE
---------------------------------

Internal error : SF_INFO struct incomplete.

**Comment by erikd** [comment] 2017-05-09 03:30
This is a duplicate of #243 .

**Closed by erikd** 2017-05-09 03:30 UTC
