### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by stefan-balke** [erikd/libsndfile#127] opened 2016-03-31 13:12 UTC
Hey @erikd,

can you guide through building this for windows?

I want to do a conda forge for this one and libsamplerate so scientific users can install this dependency very easily.

The corresponding PR is here https://github.com/conda-forge/staged-recipes/pull/231

For libsamplerate you provide a Visual Studio file but how can I create it for libsndfile?

Thanks
Stefan

**Comment by erikd** [comment] 2016-03-31 19:15
I have no idea how to build libsndfile *on* Windows. I assume you would need to use MinGW or something.

When I release a libsndfile binary installer for WIndows, I do it by cross compiling from Linux, running the test suite under Wine and then running INNO Setup under Wine.

As for libsamplerate, the Visual Studio file must be at least a decade old. I'd be surprised if it stll works.

**Comment by stefan-balke** [comment] 2016-04-04 12:36
Oh wow, this sounds hard to do in a CI tool.

Can you point me to some docu on how you do this?
Might actually be doable in a Virtual Machine...

**Comment by erikd** [comment] 2016-04-04 20:32
Why not just use the pre-compiled Windows binary I provide?

**Comment by stefan-balke** [comment] 2016-04-05 11:41
> Why not just use the pre-compiled Windows binary I provide?

That would definitely be one solution.
I think the goal of the conda-forge-project is to provide reproducible builds for all platforms...

**Comment by erikd** [comment] 2016-04-05 22:41
If you really want to build it yourself, I would suggest using the MinGw-W64 tools ( http://mingw-w64.org/doku.php ). I will even help where I can (I don't have a Windows machine and my Windows knowledge is almost non-existant). Visual Studio is unlikey to work and I have zero interest in trying to support that toolchain (see http://www.mega-nerd.com/libsndfile/FAQ.html#Q019 ).

**Comment by chadwackerman** [comment] 2016-04-15 03:10
The open source world has changed quite a bit since your dated anti-Windows rant in the FAQ. Frankly you can't even remember how to build or release this thing any more for Linux. If you'd quit screwing around and get CMake working, you'll get Windows builds for free -- including Visual Studio projects for those who care. And if you ever do a release and get this project back on track, there's plenty of people who will take a Windows dependency and help test things for you.

**Comment by jniemann66** [comment] 2016-04-15 03:41
Has anyone tried to build it recently with mingw ? I don't see why it can't be done, but maybe I'm ignorant of some horrendous issue with it.

**Comment by erikd** [comment] 2016-04-15 04:44
Building on windows with MinGW should work.

**Comment by jniemann66** [comment] 2016-04-15 04:53
Cool - I'm going to try it when I get some time.

**Comment by erikd** [comment] 2016-04-15 08:10
@chadwackerman I am really quite amazed that someone like you who has contributed so little to open source (from what I cas see on your github account) is then able to turn around and act as if I owe you something.

**Comment by chadwackerman** [comment] 2016-04-15 15:29
You haven't done a release of a project with known buffer overruns and known GPL issues in nearly half a decade. It's been so long that by your own public admission you've forgotten how to package a release. You've put up barriers to contributors. Your opinions on Windows support are dated (and frankly, out of line). And you're busy farting around with tweaky nonsense while promising to do a release as the months keep rolling by. If you'd prefer someone "open source famous" to tell you this I'm happy to have them email you.

**Comment by erikd** [comment] 2016-04-15 21:15
@chadwackerman Vesion 1.0.26 was released in November 2015.

**Comment by jcelerier** [comment] 2016-07-02 12:05
>  Why not just use the pre-compiled Windows binary I provide?

@erikd The link on the website ( http://www.mega-nerd.com/files/libsndfile-1.0.26-w32-setup.exe ) gives a 404

**Comment by erikd** [comment] 2016-07-02 21:37
What browser are you using? I just checked in Firefox and Chrome, and both corrected provided the correct link.

Also, why not use 1.0.27? 10.2.6 had a few minor bugs.

**Closed by erikd** 2016-07-02 21:37 UTC

**Comment by uklauer** [comment] 2016-07-02 22:34
It seems the problem is the top page, http://www.mega-nerd.com/ itself, which currently shows a broken and outdated (1.0.26) version of http://www.mega-nerd.com/libsndfile/ instead of the expected overview page (https://web.archive.org/web/20160327070255/http://www.mega-nerd.com/).

**Comment by jcelerier** [comment] 2016-07-02 22:45
Indeed, this is what I have on the website : 
![sndfile](https://cloud.githubusercontent.com/assets/2772730/16542781/72499d12-40b7-11e6-8ada-0cbf6e41f15f.png)

**Comment by erikd** [comment] 2016-07-02 23:36
@uklauer Yes, the top level page got overwritten at some stage. Fixed now.
