### ISSUE TITLE
File to be write is not accessible

### ISSUE THREAD

**Issue by JeyanthInba** [erikd/libsndfile#410] opened 2018-09-10 07:22 UTC
The file pointer is always null.Also sf_error command returns '5'.
Here **AudioFilePointer** is my file pointer which is always NULL.

Could you please support in this.
Thanks in advance!

 ```
memset(&sfinfo, 0, sizeof(SF_INFO));
    sfinfo.samplerate = 48000;
    sfinfo.channels = 2;
    sfinfo.format = SF_FORMAT_RAW|SF_FORMAT_PCM_16|SF_ENDIAN_LITTLE;
    AudioFilePointer =sf_open("/mnt/sdcard/MainActivity/Buffer_SND_Audio1.pcm", SFM_WRITE, &sfinfo); int error = sf_error(AudioFilePointer);
     __android_log_print(ANDROID_LOG_DEBUG, "error", "error = %d\n", error);

```

**Comment by erikd** [comment] 2018-09-10 08:26
Instead of using `sf_error` which returns a rather un-interesting integer, you should instead be using `sf_error_str` which returns a printable string.

**Comment by JeyanthInba** [comment] 2018-09-10 11:39
`Error : major format is 0`

This error is coming.
I want to write a pcm file.Could you please tell me the format or syntax.
Kindly help,I am struck in this the whole day.
Thanks in advance!

**Comment by erikd** [comment] 2018-09-11 00:45
> `Error : major format is 0`

If you get that from the code above, it looks like libsndfile might have been incorrectly built. If you built it yourself, did you run the test suite and did everything pass? If you didn't build it yourself you need to contact whoever did build it.

**Comment by JeyanthInba** [comment] 2018-09-11 03:53
Thank you so much! I ll check this.

**Comment by JeyanthInba** [comment] 2018-09-11 07:33
I am using Sndlib in android programming..Almost i built the code but some dependencies it is asking.
Could you please tell me about building the lib in android.

**Comment by JeyanthInba** [comment] 2018-09-11 10:04
```
jeyanth@jeyanthi /cygdrive/c/Users/Jeyanth/Desktop/libsndfile-master
$ ./autogen.sh
checking for autogen ... yes
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... libtoolize
checking for pkg-config ... yes
checking for python ...
You must have Python installed to compile libsndfile.
Download the appropriate package for your distribution,
or get the source tarball at http://python.org/
no

jeyanth@jeyanthi /cygdrive/c/Users/Jeyanth/Desktop/libsndfile-master
$ ./autogen.sh
checking for autogen ... yes
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... libtoolize
checking for pkg-config ... yes
checking for python ... yes
Generating configuration files for libsndfile, please wait ...
  aclocal
  libtoolize --automake --force
  autoheader
  automake --add-missing
configure.ac:58: installing 'build-aux/ar-lib'
configure.ac:38: installing 'build-aux/compile'
configure.ac:28: installing 'build-aux/config.guess'
configure.ac:28: installing 'build-aux/config.sub'
configure.ac:33: installing 'build-aux/install-sh'
configure.ac:33: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
  autoconf

jeyanth@jeyanthi /cygdrive/c/Users/Jeyanth/Desktop/libsndfile-master
$ export ANDROID_TOOLCHAIN_HOME=C:/Users/Jeyanth/AppData/Local/Android

jeyanth@jeyanthi /cygdrive/c/Users/Jeyanth/Desktop/libsndfile-master
$ ./Scripts/android-configure.sh
Error : ANDROID_PREFIX 'C:/Users/Jeyanth/AppData/Local/Android/android-ndk-r8e/toolchains/arm-linux-androideabi-4.7/prebuilt/cygwin_nt-10.0-x86_64' does not exist.
```



This is my Cygwin Terminal commands.
**cygwin_nt-10.0-x86_64** --what is this,How to make it work?

Also i tried to install the cygwin toolchain in android but it is not turning up.
The below error is coming

```
jeyanth@jeyanthi /cygdrive/c/Users/Jeyanth/AppData/Local/Android/android-ndk-r8e/build/tools
$ ./make_standalone_toolchain.py --arch arm --api 17 --stl=libc++ --install-dir=c:/Cygwin
Unsupported platform: CYGWIN_NT-10.0
```

how to solve this **Unsupported platform: CYGWIN_NT-10.0**..

Need your support:(

**Comment by evpobr** [comment] 2018-09-11 10:11
> You must have Python installed to compile libsndfile.

**Comment by JeyanthInba** [comment] 2018-09-11 11:03
Yes it is already installed

**Comment by evpobr** [comment] 2018-09-11 11:04
It was output of your configure. If it is installed, it is not found correctly.

**Comment by JeyanthInba** [comment] 2018-09-11 11:09
After installing only it allow us to proceed right?
Can be more specific please!

**Comment by JeyanthInba** [comment] 2018-09-11 11:10
```
jeyanth@jeyanthi /cygdrive/c/Users/Jeyanth/Desktop/libsndfile-master
$ ./autogen.sh
checking for autogen ... yes
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... libtoolize
checking for pkg-config ... yes
checking for python ... yes
Generating configuration files for libsndfile, please wait ...
```
**checking for python ... yes**
check here

**Comment by evpobr** [comment] 2018-09-11 11:14
Yes, i see now.

I don't know what problem is. Both Cygwin and Android are not officially supported. We got reports about bugs on that platforms. 

Can you insert content of `config.h` and `sndfile.h` files? Maybe it could help?

**Comment by JeyanthInba** [comment] 2018-09-11 11:18
[Files.zip](https://github.com/erikd/libsndfile/files/2370733/Files.zip)


PFA

**Comment by evpobr** [comment] 2018-09-11 11:55
Cannot reproduce this with small test on Windows. But i've noticed your `libsndfile` version is 1.0.25. it is 7 years old, Take latest sources from this repo and try to rebuild. Maybe this bug was fixed in next releases.

**Comment by JeyanthInba** [comment] 2018-09-11 11:57
Do you have any .a (static library) file,so that i can add it in android program.kindly share if you have satic libsnd library for android

**Comment by JeyanthInba** [comment] 2018-09-11 12:05
` ./Scripts/android-configure.sh`
Could you please tell me after this command what i need to do?

**Comment by evpobr** [comment] 2018-09-11 12:12
Everything we know is [here](https://github.com/erikd/libsndfile/blob/master/Building-for-Android.md).

**Comment by JeyanthInba** [comment] 2018-09-11 12:19
`Since I (erikd), do almost zero Android development, I am happy accept patches for this documentation and script to improve its utility for real Android developers.`

No one have given documentation for this still?

Ok fine. If i found successful,Surely I ll give a perfect documentation for android developers.
Thank you for your Support!
Please let me know if any update on this.

**Closed** 2018-12-19 07:45 UTC
